version: 2
updates:
  - package-ecosystem: bundler
    directory: "/apps/fintr-be"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/apps/fintr-fe"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
