# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rspec
  - rubocop-performance

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: True

Rails/TimeZone:
  Enabled: true
  EnforcedStyle: strict

Layout/ArrayAlignment:
  Enabled: true

Layout/HashAlignment:
  Enabled: true

RSpec/NestedGroups:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/ChangeByZero:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Style/HashSyntax:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

RSpec/RepeatedSubjectCall:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/MessageSpies:
  Enabled: true
  Exclude:
    - spec/jobs/transactions/check_duplicate_today_job_spec.rb
    - spec/operations/insights/operations/create_insights_data_spec.rb
    - spec/operations/insights/operations/create_summary_structure_spec.rb
    - spec/operations/insights/operations/create_weekly_spending_spec.rb

RSpec/NamedSubject:
  Enabled: true
  Exclude:
    - spec/operations/insights/operations/create_summary_structure_spec.rb
    - spec/operations/insights/operations/create_weekly_spending_spec.rb
    - spec/operations/insights/operations/create_insights_data_spec.rb

RSpec/StubbedMock:
  Enabled: true
  Exclude:
    - spec/operations/insights/operations/create_insights_data_spec.rb
    - spec/operations/insights/operations/create_summary_structure_spec.rb
    - spec/operations/insights/operations/create_weekly_spending_spec.rb

RSpec/MessageChain:
  Enabled: true
  Exclude:
    - spec/operations/budgets/operations/update_budget_spec.rb

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space
