# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

plugins:
  - rubocop-rails-omakase
  - rubocop-rspec
  - rubocop-performance

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: True

Rails/TimeZone:
  Enabled: true
  EnforcedStyle: strict

Layout/ArrayAlignment:
  Enabled: true

Layout/HashAlignment:
  Enabled: true
