[build]
builder = "docker"
dockerfile = "Dockerfile"

[build.args]
NEXT_PUBLIC_APP_BASE_URL = "${NEXT_PUBLIC_APP_BASE_URL}"
NEXT_PUBLIC_BE_URL = "${NEXT_PUBLIC_BE_URL}"
NEXT_PUBLIC_AUTH0_DOMAIN = "${NEXT_PUBLIC_AUTH0_DOMAIN}"
NEXT_PUBLIC_AUTH0_CLIENT_ID = "${NEXT_PUBLIC_AUTH0_CLIENT_ID}"
NEXT_PUBLIC_AUTH0_CLIENT_SECRET = "${NEXT_PUBLIC_AUTH0_CLIENT_SECRET}"
NEXT_PUBLIC_AUTH0_AUDIENCE = "${NEXT_PUBLIC_AUTH0_AUDIENCE}"
NEXT_PUBLIC_ENVIRONMENT = "${NEXT_PUBLIC_ENVIRONMENT}"
NEXT_PUBLIC_SENTRY_DSN = "${NEXT_PUBLIC_SENTRY_DSN}"
AUTH0_SECRET = "${AUTH0_SECRET}"
SENTRY_ORG = "${SENTRY_ORG}"
SENTRY_PROJECT = "${SENTRY_PROJECT}"
SENTRY_AUTH_TOKEN = "${SENTRY_AUTH_TOKEN}"
SENTRY_DSN = "${SENTRY_DSN}"

[deploy]
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
