import { TutorialStep, TutorialConfig } from '@/contexts/TutorialContext';

export const desktopTutorialSteps: TutorialStep[] = [
  {
    id: 'add-transaction-button',
    title: 'Add Transaction',
    description: 'Click the "Add Transaction" button to create different types of transactions.',
    targetSelector: '[data-tutorial-target="add-transaction-button"]',
    position: 'bottom',
  },
  {
    id: 'expense-tab',
    title: 'Expense Tab',
    description: 'The Expense tab is where you record your spending and expenses.',
    targetSelector: '[data-tutorial-target="expense-tab"]',
    position: 'bottom',
    waitForElement: true,
  },
  {
    id: 'income-tab',
    title: 'Income Tab',
    description: 'The Income tab is where you record your earnings. You can also deduct taxes and contributions here.',
    targetSelector: '[data-tutorial-target="income-tab"]',
    position: 'bottom',
    waitForElement: true,
  },
  {
    id: 'income-form',
    title: 'Income Form',
    description: 'This is the income form where you can enter your income details.',
    targetSelector: '[data-tutorial-target="income-form"]',
    position: 'top',
    waitForElement: true,
  },
  {
    id: 'deduct-taxes',
    title: 'Deduct Taxes',
    description: 'Use this option if you want to reduce taxes that should take effect monthly for the whole year.',
    targetSelector: '[data-tutorial-target="deduct-taxes"]',
    position: 'top',
    waitForElement: true,
  },
  {
    id: 'deduct-contributions',
    title: 'Deduct Contributions',
    description: 'Use this option if you want to reduce government contributions (SSS, PhilHealth, Pag-IBIG) from your income.',
    targetSelector: '[data-tutorial-target="deduct-contributions"]',
    position: 'top',
    waitForElement: true,
  },
  {
    id: 'transfer-tab',
    title: 'Transfer Tab',
    description: 'This is what you\'ll use to transfer cash from one account to another.',
    targetSelector: '[data-tutorial-target="transfer-tab"]',
    position: 'bottom',
    waitForElement: true,
  },
  {
    id: 'loan-tab',
    title: 'Loan Tab',
    description: 'This is what you use to register loans whether you\'re the borrower or the lender. Try adding a percentage to see how much you\'ll lose or earn from the loan schedule.',
    targetSelector: '[data-tutorial-target="loan-tab"]',
    position: 'bottom',
    waitForElement: true,
  },
  {
    id: 'transaction-close',
    title: 'Close Transaction Modal',
    description: 'Click the "X" button to close the Add Transaction modal and return to the dashboard.',
    targetSelector: '[data-tutorial-target="transaction-close"]',
    position: 'top',
    waitForElement: true,
  },
  {
    id: 'dashboard-loan-tab',
    title: 'View Loans',
    description: 'Click on the "Loans" tab to view the loans you\'ve created. You can see the loan schedule and how much you can earn here.',
    targetSelector: '[data-tutorial-target="dashboard-loan-tab"]',
    position: 'bottom',
  },
  {
    id: 'add-receipt-button',
    title: 'Add Receipt',
    description: 'Click "Add Receipt" to upload receipt images and automatically extract transaction details.',
    targetSelector: '[data-tutorial-target="add-receipt-button"]',
    position: 'bottom',
  },
  {
    id: 'take-photo',
    title: 'Take Photo',
    description: 'Use this option to take photos of your receipts directly from your device.',
    targetSelector: '[data-tutorial-target="take-photo"]',
    position: 'top',
    waitForElement: true,
    action: 'highlight-only',
  },
  {
    id: 'upload-file',
    title: 'Upload File',
    description: 'Use this option to upload receipt image files from your device.',
    targetSelector: '[data-tutorial-target="upload-file"]',
    position: 'top',
    waitForElement: true,
    action: 'highlight-only',
  },
  {
    id: 'add-receipt-modal',
    title: 'Add Receipt Feature',
    description: 'This feature helps identify inputs from your receipt like amount, date, account, and category automatically.',
    targetSelector: '[data-tutorial-target="add-receipt-modal"]',
    position: 'top',
    waitForElement: true,
    action: 'highlight-only',
  },
  {
    id: 'close-add-receipt-modal',
    title: 'Close Add Receipt Modal',
    description: 'Click the "X" button to close the Add Receipt modal and return to the dashboard.',
    targetSelector: '[data-tutorial-target="close-add-receipt-modal"]',
    position: 'top',
    waitForElement: true,
  },
  {
    id: 'dashboard-tab',
    title: 'Dashboard Tab',
    description: 'Click on the "Dashboard" tab to view your financial overview and insights.',
    targetSelector: '[data-tutorial-target="dashboard-tab"]',
    position: 'bottom',
    waitForElement: true,
  },
  {
    id: 'dashboard-summary',
    title: 'Dashboard Summary',
    description: 'This section shows your total income, total expenses, and net savings for a quick overview of your financial performance.',
    targetSelector: '[data-tutorial-target="dashboard-summary"]',
    position: 'top',
    waitForElement: true,
    action: 'highlight-only',
  },
  {
    id: 'financial-health-score',
    title: 'Financial Health Score',
    description: 'This score gives you an overall rating based on your budget usage and savings, helping you understand your financial health.',
    targetSelector: '[data-tutorial-target="financial-health-score"]',
    position: 'top',
    waitForElement: true,
    action: 'highlight-only',
  },
  {
    id: 'expense-breakdown',
    title: 'Expense Breakdown',
    description: 'This pie chart shows how your expenses are distributed across different categories, helping you see where your money goes.',
    targetSelector: '[data-tutorial-target="expense-breakdown"]',
    position: 'top',
    waitForElement: true,
    action: 'highlight-only',
  },
];

export const mobileTutorialSteps: TutorialStep[] = [
  {
    id: 'mobile-add-button',
    title: 'The "+" Button',
    description: 'Tap the "+" button to see available options for adding transactions and receipts.',
    targetSelector: '[data-tutorial-target="mobile-add-button"]',
    position: 'top',
    action: 'open-menu',
  },
  {
    id: 'mobile-add-transaction',
    title: 'Add Transaction',
    description: 'Tap "Add Transaction" to create different types of transactions.',
    targetSelector: '[data-tutorial-target="mobile-add-transaction"]',
    position: 'top',
    waitForElement: true,
    action: 'click-menu-item',
  },
  {
    id: 'expense-tab',
    title: 'Expense Tab',
    description: 'The Expense tab is where you record your spending and expenses.',
    targetSelector: '[data-tutorial-target="expense-tab"]',
    position: 'bottom',
    waitForElement: true,
  },
  {
    id: 'income-tab',
    title: 'Income Tab',
    description: 'The Income tab is where you record your earnings. You can also deduct taxes and contributions here.',
    targetSelector: '[data-tutorial-target="income-tab"]',
    position: 'bottom',
    waitForElement: true,
  },
  {
    id: 'income-form',
    title: 'Income Form',
    description: 'This is the income form where you can enter your income details.',
    targetSelector: '[data-tutorial-target="income-form"]',
    position: 'top',
    waitForElement: true,
  },
  {
    id: 'deduct-taxes',
    title: 'Deduct Taxes',
    description: 'Use this option if you want to reduce taxes that should take effect monthly for the whole year.',
    targetSelector: '[data-tutorial-target="deduct-taxes"]',
    position: 'top',
    waitForElement: true,
  },
  {
    id: 'deduct-contributions',
    title: 'Deduct Contributions',
    description: 'Use this option if you want to reduce government contributions (SSS, PhilHealth, Pag-IBIG) from your income.',
    targetSelector: '[data-tutorial-target="deduct-contributions"]',
    position: 'top',
    waitForElement: true,
  },
  {
    id: 'transfer-tab',
    title: 'Transfer Tab',
    description: 'This is what you\'ll use to transfer cash from one account to another.',
    targetSelector: '[data-tutorial-target="transfer-tab"]',
    position: 'bottom',
    waitForElement: true,
  },
  {
    id: 'loan-tab',
    title: 'Loan Tab',
    description: 'This is what you use to register loans whether you\'re the borrower or the lender. Try adding a percentage to see how much you\'ll lose or earn from the loan schedule.',
    targetSelector: '[data-tutorial-target="loan-tab"]',
    position: 'bottom',
    waitForElement: true,
  },
  {
    id: 'close-modal-button',
    title: 'Close Modal',
    description: 'Tap the "X" button to close the Add Transaction modal and return to the dashboard.',
    targetSelector: '[data-tutorial-target="transaction-close"]',
    position: 'top',
    waitForElement: true,
  },
  {
    id: 'mobile-menu-button',
    title: 'Menu',
    description: 'Tap the "Menu" button to access additional features and settings.',
    targetSelector: '[data-tutorial-target="mobile-menu-button"]',
    position: 'top',
  },
  {
    id: 'loan-menu-item',
    title: 'Loans',
    description: 'Tap on "Loans" to view the loans you\'ve created. You can see the loan schedule and how much you can earn here.',
    targetSelector: '[data-tutorial-target="loan-menu-item"]',
    position: 'top',
    waitForElement: true,
  },
  {
    id: 'mobile-add-receipt-button',
    title: 'Add Receipt',
    description: 'Tap the "+" button again, let\'s go over and see the "Add Receipt" functionality.',
    targetSelector: '[data-tutorial-target="mobile-add-button"]',
    position: 'top',
    action: 'open-menu',
  },
  {
    id: 'mobile-add-receipt',
    title: 'Add Receipt',
    description: 'Tap "Add Receipt" from the menu.',
    targetSelector: '[data-tutorial-target="mobile-add-receipt"]',
    position: 'top',
    waitForElement: true,
    action: 'click-menu-item',
  },
  {
    id: 'take-photo',
    title: 'Take Photo',
    description: 'Use this option to take photos of your receipts directly from your device.',
    targetSelector: '[data-tutorial-target="take-photo"]',
    position: 'top',
    waitForElement: true,
    action: 'highlight-only',
  },
  {
    id: 'upload-file',
    title: 'Upload File',
    description: 'Use this option to upload receipt image files from your device.',
    targetSelector: '[data-tutorial-target="upload-file"]',
    position: 'top',
    waitForElement: true,
    action: 'highlight-only',
  },
  {
    id: 'add-receipt-modal',
    title: 'Add Receipt Feature',
    description: 'This feature helps identify inputs from your receipt like amount, date, account, and category automatically.',
    targetSelector: '[data-tutorial-target="add-receipt-modal"]',
    position: 'top',
    waitForElement: true,
    action: 'highlight-only',
  },
  {
    id: 'close-add-receipt-modal',
    title: 'Close Add Receipt Modal',
    description: 'Tap the "X" button to close the Add Receipt modal and return to the dashboard.',
    targetSelector: '[data-tutorial-target="close-add-receipt-modal"]',
    position: 'top',
    waitForElement: true,
  },
  {
    id: 'dashboard-tab',
    title: 'Dashboard Tab',
    description: 'Tap on the "Dashboard" tab to view your financial overview and insights.',
    targetSelector: '[data-tutorial-target="mobile-dashboard-button"]',
    position: 'top',
    waitForElement: true,
  },
  {
    id: 'dashboard-summary',
    title: 'Dashboard Summary',
    description: 'This section shows your total income, total expenses, and net savings for a quick overview of your financial performance.',
    targetSelector: '[data-tutorial-target="dashboard-summary"]',
    position: 'top',
    waitForElement: true,
    action: 'highlight-only',
  },
  {
    id: 'financial-health-score',
    title: 'Financial Health Score',
    description: 'This score gives you an overall rating based on your budget usage and savings, helping you understand your financial health.',
    targetSelector: '[data-tutorial-target="financial-health-score"]',
    position: 'top',
    waitForElement: true,
    action: 'highlight-only',
  },
  {
    id: 'expense-breakdown',
    title: 'Expense Breakdown',
    description: 'This pie chart shows how your expenses are distributed across different categories, helping you see where your money goes.',
    targetSelector: '[data-tutorial-target="expense-breakdown"]',
    position: 'top',
    waitForElement: true,
    action: 'highlight-only',
  },
];

export const getTutorialConfig = (platform: 'desktop' | 'mobile'): TutorialConfig => {
  const steps = platform === 'desktop' ? desktopTutorialSteps : mobileTutorialSteps;
  return { steps };
};
