<% require "dotenv"; Dotenv.load(".env.staging") %>
# Name of your application. Used to uniquely configure containers.
service: fintr-be

# Name of the container image.
image: adminfintr/fintr-be

# Healthcheck configuration for the service
healthcheck:
  path: /up
  port: 3000
  max_attempts: 12
  interval: 5s

# Deploy to these servers.
servers:
  web:
    hosts:
      - ec2-3-27-154-204.ap-southeast-2.compute.amazonaws.com
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: ec2-3-27-154-204.ap-southeast-2.compute.amazonaws.com
  app_port: 3000 # The port your application container listens on (default: 80)
  healthcheck:
    path: /up # The path for the health check endpoint in your app (default: /up)
    interval: 10 # How often to check (default: 1s)
    timeout: 15 # Timeout for the health check request (default: 5s)
    max_attempts: 10 # Maximum number of health check attempts
  # Other options like buffering, logging, response_timeout, etc.

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: 
    - KAMAL_REGISTRY_USERNAME

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  args:
    RUBY_VERSION: "<%= Pathname.pwd.join('.ruby-version').read.strip.delete_prefix('ruby-').delete_prefix('ruby ') %>"
    BUNDLER_VERSION: 2.6.2
    RAILS_MASTER_KEY:
      - RAILS_MASTER_KEY

  # Pass in additional build args needed for your Dockerfile.
  # args:
  #   RUBY_VERSION: <%= ENV["RBENV_VERSION"] || ENV["rvm_ruby_string"] || "#{RUBY_ENGINE}-#{RUBY_ENGINE_VERSION}" %>

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - AUTH0_URL
    - AUTH0_AUDIENCE
    - CLIENT_URL
    - CORS_ORIGINS
    - RACK_ENV
    - RAILS_ENV
    - PORT
    - USER_AUTH0_ID
    - DATABASE_USER
    - DATABASE_PASSWORD
    - DATABASE_HOST
    - DB_BASE_URL
    - SENTRY_DSN

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal app logs -r job" will tail logs from the first server in the job section.
#
# aliases:
#   shell: app exec --interactive --reuse "bash"

# Use a different ssh user than root
#
ssh:
  user: ubuntu

# Use a persistent storage volume.
#
# volumes:
#   - "app_storage:/app/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
#
# asset_path: /app/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
#
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

# Use accessory services (secrets come from .kamal/secrets).
#
# accessories:
#   db:
#     image: mysql:8.0
#     host: 192.168.0.2
#     port: 3306
#     env:
#       clear:
#         MYSQL_ROOT_HOST: '%'
#       secret:
#         - MYSQL_ROOT_PASSWORD
#     files:
#       - config/mysql/production.cnf:/etc/mysql/my.cnf
#       - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
#     directories:
#       - data:/var/lib/mysql
#   redis:
#     image: valkey/valkey:8
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data
