development:
  duplicate_transaction_daily:
    class: DuplicateTransactionDailyJob
    queue: default
    schedule: every minute

production:
  duplicate_transaction_daily:
    class: DuplicateTransactionDailyJob
    queue: default
    schedule: '@midnight Asia/Manila'
