# frozen_string_literal: true

puts "Seeding achievements catalog..."

catalog = [
  # Transactions (chronological by count)
  {
    key: "penny_pioneer",
    title: "Penny Pioneer",
    description: "Logged your first income or expense. The trail begins.",
    xp_reward: 40,
    rarity: "common",
    kind: "collectible",
    category: "transactions",
    position: 1,
    image_key: "penny_pioneer",
    unlock_event: "transaction_created",
    unlock_threshold: { "min_count" => 1 },
    active: true,
  },
  {
    key: "habit_hacker",
    title: "Habit Hacker",
    description: "Logged 10 transactions. Momentum is real.",
    xp_reward: 80,
    rarity: "uncommon",
    kind: "collectible",
    category: "transactions",
    position: 2,
    image_key: "habit_hacker",
    unlock_event: "transaction_created",
    unlock_threshold: { "min_count" => 10 },
    active: true,
  },
  {
    key: "ledger_climber",
    title: "Ledger Climber",
    description: "Logged 20 transactions. The climb continues.",
    xp_reward: 100,
    rarity: "uncommon",
    kind: "collectible",
    category: "transactions",
    position: 3,
    image_key: "ledger_climber",
    unlock_event: "transaction_created",
    unlock_threshold: { "min_count" => 20 },
    active: true,
  },
  {
    key: "fifty_strong",
    title: "Fifty Strong",
    description: "Logged 50 transactions. Consistency unlocked.",
    xp_reward: 150,
    rarity: "rare",
    kind: "collectible",
    category: "transactions",
    position: 4,
    image_key: "fifty_strong",
    unlock_event: "transaction_created",
    unlock_threshold: { "min_count" => 50 },
    active: true,
  },
  {
    key: "century_chronicler",
    title: "Century Chronicler",
    description: "Logged 100 transactions. A full century in the books.",
    xp_reward: 200,
    rarity: "rare",
    kind: "collectible",
    category: "transactions",
    position: 5,
    image_key: "century_chronicler",
    unlock_event: "transaction_created",
    unlock_threshold: { "min_count" => 100 },
    active: true,
  },
  {
    key: "double_century",
    title: "Double Century",
    description: "Logged 200 transactions. Elite logging territory.",
    xp_reward: 250,
    rarity: "rare",
    kind: "collectible",
    category: "transactions",
    position: 6,
    image_key: "double_century",
    unlock_event: "transaction_created",
    unlock_threshold: { "min_count" => 200 },
    active: true,
  },
  {
    key: "triple_tracker",
    title: "Triple Tracker",
    description: "Logged 300 transactions. Relentless record-keeping.",
    xp_reward: 300,
    rarity: "epic",
    kind: "collectible",
    category: "transactions",
    position: 7,
    image_key: "triple_tracker",
    unlock_event: "transaction_created",
    unlock_threshold: { "min_count" => 300 },
    active: true,
  },
  {
    key: "half_grand_historian",
    title: "Half-Grand Historian",
    description: "Logged 500 transactions. Your history is huge.",
    xp_reward: 400,
    rarity: "epic",
    kind: "collectible",
    category: "transactions",
    position: 8,
    image_key: "half_grand_historian",
    unlock_event: "transaction_created",
    unlock_threshold: { "min_count" => 500 },
    active: true,
  },
  {
    key: "thousand_tales",
    title: "Thousand Tales",
    description: "Logged 1000 transactions. Legendary ledger status.",
    xp_reward: 500,
    rarity: "epic",
    kind: "collectible",
    category: "transactions",
    position: 9,
    image_key: "thousand_tales",
    unlock_event: "transaction_created",
    unlock_threshold: { "min_count" => 1000 },
    active: true,
  },
  # Budgets
  {
    key: "budget_beast",
    title: "Budget Beast",
    description: "Created a budget and put spending on a leash.",
    xp_reward: 70,
    rarity: "uncommon",
    kind: "collectible",
    category: "budgets",
    position: 1,
    image_key: "budget_beast",
    unlock_event: "budget_created",
    unlock_threshold: {},
    active: true,
  },
  # Collaboration
  {
    key: "crew_caller",
    title: "Crew Caller",
    description: "Invited someone to collaborate. Money loves company.",
    xp_reward: 90,
    rarity: "rare",
    kind: "collectible",
    category: "collaboration",
    position: 1,
    image_key: "crew_caller",
    unlock_event: "access_granted",
    unlock_threshold: {},
    active: true,
  },
  # Loans
  {
    key: "first_lien",
    title: "First Lien",
    description: "Created your first loan.",
    xp_reward: 60,
    rarity: "common",
    kind: "collectible",
    category: "loans",
    position: 1,
    image_key: "first_lien",
    unlock_event: "loan_created",
    unlock_threshold: { "min_count" => 1 },
    active: true,
  },
  {
    key: "loan_stacker",
    title: "Loan Stacker",
    description: "Created 5 loans.",
    xp_reward: 120,
    rarity: "uncommon",
    kind: "collectible",
    category: "loans",
    position: 2,
    image_key: "loan_stacker",
    unlock_event: "loan_created",
    unlock_threshold: { "min_count" => 5 },
    active: true,
  },
  {
    key: "debt_dynamo",
    title: "Debt Dynamo",
    description: "Created 10 loans.",
    xp_reward: 180,
    rarity: "rare",
    kind: "collectible",
    category: "loans",
    position: 3,
    image_key: "debt_dynamo",
    unlock_event: "loan_created",
    unlock_threshold: { "min_count" => 10 },
    active: true,
  },
  # Loan payments
  {
    key: "payback_starter",
    title: "Payback Starter",
    description: "Made your first loan payment.",
    xp_reward: 50,
    rarity: "common",
    kind: "collectible",
    category: "loan_payments",
    position: 1,
    image_key: "payback_starter",
    unlock_event: "loan_payment_created",
    unlock_threshold: { "min_count" => 1 },
    active: true,
  },
  {
    key: "installment_ace",
    title: "Installment Ace",
    description: "Made 5 loan payments.",
    xp_reward: 100,
    rarity: "uncommon",
    kind: "collectible",
    category: "loan_payments",
    position: 2,
    image_key: "installment_ace",
    unlock_event: "loan_payment_created",
    unlock_threshold: { "min_count" => 5 },
    active: true,
  },
  {
    key: "repayment_pro",
    title: "Repayment Pro",
    description: "Made 10 loan payments.",
    xp_reward: 150,
    rarity: "rare",
    kind: "collectible",
    category: "loan_payments",
    position: 3,
    image_key: "repayment_pro",
    unlock_event: "loan_payment_created",
    unlock_threshold: { "min_count" => 10 },
    active: true,
  },
  # Transfers
  {
    key: "hop_starter",
    title: "Hop Starter",
    description: "Completed your first transfer.",
    xp_reward: 40,
    rarity: "common",
    kind: "collectible",
    category: "transfers",
    position: 1,
    image_key: "hop_starter",
    unlock_event: "transfer_created",
    unlock_threshold: { "min_count" => 1 },
    active: true,
  },
  {
    key: "account_hopper",
    title: "Account Hopper",
    description: "Completed 3 transfers.",
    xp_reward: 70,
    rarity: "uncommon",
    kind: "collectible",
    category: "transfers",
    position: 2,
    image_key: "account_hopper",
    unlock_event: "transfer_created",
    unlock_threshold: { "min_count" => 3 },
    active: true,
  },
  {
    key: "transfer_titan",
    title: "Transfer Titan",
    description: "Completed 5 transfers.",
    xp_reward: 100,
    rarity: "uncommon",
    kind: "collectible",
    category: "transfers",
    position: 3,
    image_key: "transfer_titan",
    unlock_event: "transfer_created",
    unlock_threshold: { "min_count" => 5 },
    active: true,
  },
  {
    key: "wire_wizard",
    title: "Wire Wizard",
    description: "Completed 10 transfers.",
    xp_reward: 150,
    rarity: "rare",
    kind: "collectible",
    category: "transfers",
    position: 4,
    image_key: "wire_wizard",
    unlock_event: "transfer_created",
    unlock_threshold: { "min_count" => 10 },
    active: true,
  },
]

%w[first_transaction budget_setter goal_starter inviter shared_space vision_setter].each do |old_key|
  achievement = Achievements::Achievement.find_by(key: old_key)
  next unless achievement

  Achievements::UserAchievement.where(achievement_id: achievement.id).delete_all
  achievement.destroy!
end

catalog.each do |attrs|
  record = Achievements::Achievement.find_or_initialize_by(key: attrs[:key])
  record.assign_attributes(attrs)
  record.save!
end

puts "Seeded #{catalog.size} achievements (grouped and chronological)."
