development:
  check_duplicate_today:
    class: Transactions::CheckDuplicateTodayJob
    queue: default
    schedule: every hour
  transfers_check_duplicate_today:
    class: Transactions::Transfers::CheckDuplicateTodayJob
    queue: default
    schedule: every hour
  accounts_calculate_pending_balances:
    class: Transactions::Accounts::CalculatePendingBalancesJob
    queue: default
    schedule: every hour
  transfers_calculate_pending_balances:
    class: Transactions::Transfers::CalculatePendingBalancesJob
    queue: default
    schedule: every hour
  budgets_create_space_monthly_budgets:
    class: Budgets::CreateSpaceMonthlyBudgetsJob
    queue: default
    schedule: every hour
  renew_free_subscription_cycles:
    class: Finance::RenewFreeSubscriptionCyclesJob
    queue: default
    schedule: every day
  revert_expired_promo_pricing:
    class: Finance::RevertExpiredPromoPricingJob
    queue: default
    schedule: every day
  trim_space_change_log:
    class: Sync::TrimChangeLogJob
    queue: default
    schedule: every day

staging:
  check_duplicate_today:
    class: Transactions::CheckDuplicateTodayJob
    queue: default
    schedule: "0 0 * * * Asia/Manila"
  transfers_check_duplicate_today:
    class: Transactions::Transfers::CheckDuplicateTodayJob
    queue: default
    schedule: "0 0 * * * Asia/Manila"
  accounts_calculate_pending_balances:
    class: Transactions::Accounts::CalculatePendingBalancesJob
    queue: default
    schedule: "15 0 * * * Asia/Manila"
  transfers_calculate_pending_balances:
    class: Transactions::Transfers::CalculatePendingBalancesJob
    queue: default
    schedule: "30 0 * * * Asia/Manila"
  budgets_create_space_monthly_budgets:
    class: Budgets::CreateSpaceMonthlyBudgetsJob
    queue: default
    schedule: "45 0 1 * * Asia/Manila"
  update_subscription_cycle_counts:
    class: Finance::ReconcileSubscriptionCycleCountsJob
    queue: default
    schedule: "*/10 * * * * Asia/Manila"
  renew_free_subscription_cycles:
    class: Finance::RenewFreeSubscriptionCyclesJob
    queue: default
    schedule: "0 1 * * * Asia/Manila"
  revert_expired_promo_pricing:
    class: Finance::RevertExpiredPromoPricingJob
    queue: default
    schedule: "30 1 * * * Asia/Manila"
  trim_space_change_log:
    class: Sync::TrimChangeLogJob
    queue: default
    schedule: "0 2 * * * Asia/Manila"

production:
  check_duplicate_today:
    class: Transactions::CheckDuplicateTodayJob
    queue: default
    schedule: "0 0 * * * Asia/Manila"
  transfers_check_duplicate_today:
    class: Transactions::Transfers::CheckDuplicateTodayJob
    queue: default
    schedule: "0 0 * * * Asia/Manila"
  accounts_calculate_pending_balances:
    class: Transactions::Accounts::CalculatePendingBalancesJob
    queue: default
    schedule: "15 0 * * * Asia/Manila"
  transfers_calculate_pending_balances:
    class: Transactions::Transfers::CalculatePendingBalancesJob
    queue: default
    schedule: "30 0 * * * Asia/Manila"
  budgets_create_space_monthly_budgets:
    class: Budgets::CreateSpaceMonthlyBudgetsJob
    queue: default
    schedule: "45 0 1 * * Asia/Manila"
  update_subscription_cycle_counts:
    class: Finance::ReconcileSubscriptionCycleCountsJob
    queue: default
    schedule: "*/10 * * * * Asia/Manila"
  renew_free_subscription_cycles:
    class: Finance::RenewFreeSubscriptionCyclesJob
    queue: default
    schedule: "0 1 * * * Asia/Manila"
  revert_expired_promo_pricing:
    class: Finance::RevertExpiredPromoPricingJob
    queue: default
    schedule: "30 1 * * * Asia/Manila"
  trim_space_change_log:
    class: Sync::TrimChangeLogJob
    queue: default
    schedule: "0 2 * * * Asia/Manila"
